from . import batiment
from . import chambre
from . import commodite
from . import hotel_service
from . import type_chambre
from . import espace
from . import employe
from . import reservation
from . import paiement
from . import client